CONTIKI_PROJECT = udp-client udp-server
all: $(CONTIKI_PROJECT)


# Added to make the Routing RPL classic
MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC
TARGET_LIBFILES = -lm

CONTIKI=../..
include $(CONTIKI)/Makefile.include
